name: marhom
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: '>=3.3.2 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  bloc: ^8.1.4 # A predictable state management library that helps implement the BLoC (Business Logic Component) design pattern.
  cached_network_image: ^3.3.1 # Saving images for offline use
  conditional_builder_null_safety: ^0.0.6 # Show UI elements according to conditional type
  connectivity_plus: ^6.0.3
  country_code_picker: ^3.0.0 #
  cupertino_icons: ^1.0.8 # The following adds the Cupertino Icons font to your application.
  dartz: ^0.10.1 # A type-safe functional programming library for Dart.
  dio: ^5.4.3+1 # A lightweight HTTP client for Dart.
  envied: ^0.5.4+1 # Explicitly reads environment variables into a dart file from a .env file for more security and faster start up times.
  equatable: ^2.0.5 # A Dart package that helps to implement value based equality
  firebase_core: ^2.27.0 # Flutter plugin for Firebase Core, enabling connecting to multiple Firebase apps.
  firebase_messaging: ^14.7.10 # Flutter plugin for Firebase Cloud Messaging.
  flutter_bloc: ^8.1.5 # Flutter Widgets that make it easy to implement the BLoC (Business Logic Component) design pattern.
  flutter_launcher_icons: ^0.13.1 # A package which simplifies the task of updating your Flutter app's launcher icon
  flutter_native_splash: ^2.3.0 # Customize Flutter's default white native splash screen with background color and splash image
  flutter_screenutil: ^5.9.1
  flutter_svg: ^2.0.10+1 # An SVG rendering and widget library for Flutter
  freezed_annotation: ^2.4.1 # Annotations for the freezed code-generator. This package does nothing without freezed too.
  gap: ^3.0.1 # Better SizedBoxes
  get_it: ^7.7.0 # Simple direct Service Locator
  flutter_localizations:
    sdk: flutter
  intl: ^0.18.0 # internationalized/localized code formatting
  json_annotation: ^4.9.0 # Classes and helper functions that support JSON code generation via the `json_serializable` package.
  logger: ^2.3.0
  material_design_icons_flutter: ^7.0.7296 # Material icons made by community
  permission_handler: ^11.3.1
  pinput: ^4.0.0 # Adding verification code fields
  pretty_dio_logger: ^1.3.1 #  Better visualization for API response
  rxdart: ^0.27.7
  shared_preferences: ^2.2.3 # Flutter plugin for reading and writing simple key-value pairs.

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.10 # A build system for Dart code generation and modular compilation.
  envied_generator: ^0.5.4+1 # Generates .env files / Generator for the Envied package.
  flutter_lints: ^4.0.0 # Recommended lints for Flutter apps, packages, and plugins to encourage good coding practices.
  freezed: ^2.5.3 # Code generation for immutable classes that has a simple syntax/API without compromising on the features.
  json_serializable: ^6.8.0 #Automatically generate code for converting to and from JSON by annotating Dart classes.

flutter_intl:
  enabled: true

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/svg/

  fonts:
    - family: Cocon Pro
      fonts:
        - asset: assets/fonts/CoconPro-Light.otf
          weight: 300
        - asset: assets/fonts/CoconPro-Regular.otf
          weight: 400
        - asset: assets/fonts/CoconPro-Bold.otf
          weight: 700

